/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class CheckFeaturesController {
    global CheckFeaturesController() {

    }
    @RemoteAction
    global static void checkFeatures() {

    }
    @RemoteAction
    global static void checkLicenses() {

    }
    @RemoteAction
    global static Boolean checkSetup() {
        return null;
    }
    @RemoteAction
    global static Boolean isApplicationRegistered() {
        return null;
    }
}
