/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class RunOrgStaticCodeAnalysis {
    global RunOrgStaticCodeAnalysis() {

    }
    @InvocableMethod(label='Org Static Code Analysis' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RunOrgStaticCodeAnalysis.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Org Id' required=true)
    global Id orgId;
    global InvocableVariables() {

    }
}
}
