/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class DeployLater implements System.Schedulable {
    global Id deploymentId {
        get;
        set;
    }
    global DeployLater(Id deploymentId) {

    }
    global void execute(System.SchedulableContext sc) {

    }
}
