/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class GarbageCollectorBatch implements Database.Batchable<String>, Database.Stateful {
    global GarbageCollectorBatch(Map<String,Set<Id>> workItemIdsByObjectName) {

    }
    global void execute(Database.BatchableContext bc, List<String> scope) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global System.Iterable start(Database.BatchableContext bc) {
        return null;
    }
}
