/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class ValueStreamMapWorkItemCollectorBatch implements Database.Batchable<SObject>, Database.Stateful {
    global ValueStreamMapWorkItemCollectorBatch(List<copadovsm__Value_Stream_Map__c> valueStreamMaps, Integer index, List<String> workItemIds) {

    }
    global ValueStreamMapWorkItemCollectorBatch(List<copadovsm__Value_Stream_Map__c> valueStreamMaps, Integer index, List<String> workItemIds, Boolean isRecalculate) {

    }
    global void execute(Database.BatchableContext bc, List<SObject> scope) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return null;
    }
}
