/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class RunSeleniumTestGroup {
    global RunSeleniumTestGroup() {

    }
    @InvocableMethod(label='Invoke Selenium Test Group' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RunSeleniumTestGroup.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Selenium Group Id' required=true)
    global Id groupId;
    global InvocableVariables() {

    }
}
}
