/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class TakeGitSnapshot {
    global TakeGitSnapshot() {

    }
    @InvocableMethod(label='Take a git snapshot' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.TakeGitSnapshot.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Snaphot Id' required=true)
    global Id snapshotId;
    global InvocableVariables() {

    }
}
}
