/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class RunUserStoryStaticCodeAnalysis {
    global RunUserStoryStaticCodeAnalysis() {

    }
    @InvocableMethod(label='User Story Static Code Analysis' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RunUserStoryStaticCodeAnalysis.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Org Id' required=true)
    global Id orgId;
    @InvocableVariable(label='User Story Id' required=true)
    global Id storyId;
    global InvocableVariables() {

    }
}
}
