/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class RecalculateDeploymentFlowBranchStatuses {
    global RecalculateDeploymentFlowBranchStatuses() {

    }
    @InvocableMethod(label='Recalculate Deployment Flow Branch Statuses' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RecalculateDeploymentFlowBranchStatuses.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Deployment Flow Id' required=true)
    global Id flowId;
    global InvocableVariables() {

    }
}
}
