/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class ValueStreamMapEventEraserBatch implements Database.Batchable<Id>, Database.Stateful {
    global ValueStreamMapEventEraserBatch(List<Id> workItemIds, List<Id> stageIds, List<Id> blockIds) {

    }
    global ValueStreamMapEventEraserBatch(List<Id> workItemIds, List<Id> stageIds, List<Id> blockIds, List<copadovsm__Value_Stream_Map__c> valueStreamMaps) {

    }
    global void execute(Database.BatchableContext bc, List<Id> scope) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global System.Iterable start(Database.BatchableContext bc) {
        return null;
    }
}
