/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class WorkManager {
    global static copado.WorkManager.PanelPlusJson addConfig(String selectedState, String occupiedState, String AdditionalQuery, String dmlType) {
        return null;
    }
    @RemoteAction
    global static copado.WorkManager.PanelData changeConfig(String selectedState) {
        return null;
    }
    @RemoteAction
    global static copado.WorkManager.PanelData removeConfig(String selectedState) {
        return null;
    }
    @RemoteAction
    global static String saveCurrentTables(String objListFromPage, String put2wholeMap, String selectedState, List<String> currentTableOrder) {
        return null;
    }
    @RemoteAction
    global static void saveNewClause(String rid, String qObject, String clause) {

    }
    @RemoteAction
    global static void saveStatusOrders(List<String> rIds, String statusName) {

    }
    @RemoteAction
    global static copado.WorkManager.TableWrapper usList(String tableHeader, String whereClause, String additionalQuery) {
        return null;
    }
global class PWrapper {
}
global class PanelData {
}
global class PanelPlusJson {
}
global class TableWrapper {
}
global class UserStates {
}
global class UserStoryWrapper {
}
}
