/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class ValueStreamMapProxy {
    global ValueStreamMapProxy() {

    }
    global void generateEvents(Id vsmId, Datetime startDate, Datetime endDate) {

    }
    global void generateEvents(List<Id> ids) {

    }
global class InvocableVariablesDTO {
    @InvocableVariable(label='field history tracking endDate' required=false)
    global Datetime endDate;
    @InvocableVariable(label='field history tracking startDate' required=false)
    global Datetime startDate;
    @InvocableVariable(label='Value Stream Map Id' required=true)
    global Id vsmId;
    global InvocableVariablesDTO() {

    }
}
}
