/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class IndexMetadataJob implements Database.Batchable<SObject>, Database.Stateful, System.Schedulable {
    global IndexMetadataJob() {

    }
    global void execute(System.SchedulableContext sContext) {

    }
    global void execute(Database.BatchableContext bContext, List<copado__User_Story__c> scope) {

    }
    global void finish(Database.BatchableContext bContext) {

    }
    global Database.QueryLocator start(Database.BatchableContext bContext) {
        return null;
    }
}
