/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class RunContinuousIntegration {
    global RunContinuousIntegration() {

    }
    @InvocableMethod(label='Invoke Continuous Integration' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RunContinuousIntegration.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Continuous Integration Id' required=true)
    global Id ciId;
    global InvocableVariables() {

    }
}
}
