/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
@RestResource(urlMapping='/SeleniumTestCaseViewEdit')
global class SeleniumTestCaseViewEdit {
    global static copado.SeleniumTestCaseViewEdit.TestCaseInfo getTestCaseInfo(Id TestCaseId) {
        return null;
    }
    @HttpGet
    global static copado.SeleniumTestCaseViewEdit.TestCaseInfo testCaseLoadAll() {
        return null;
    }
    @HttpPost
    global static copado.SeleniumTestCaseViewEdit.TestCaseInfo testCaseSaveAll(Id testCaseId, String versionString, String name, String testCaseSrc, String testDataSrc) {
        return null;
    }
    global static copado.SeleniumTestCaseViewEdit.TestCaseInfo testCaseSaveAllImpl(Id testCaseId, String versionString, String name, String testCaseSrc, String testDataSrc) {
        return null;
    }
global class TestCaseDatasets {
    global TestCaseDatasets() {

    }
}
global class TestCaseInfo {
    global TestCaseInfo() {

    }
}
global class TestCaseNameAndVersion {
    global TestCaseNameAndVersion() {

    }
}
}
