/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class RefreshOrgMetadataCache {
    global RefreshOrgMetadataCache() {

    }
    @InvocableMethod(label='Refresh Org Metadata Cache' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RefreshOrgMetadataCache.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Org Credentials Id' required=true)
    global Id orgId;
    global InvocableVariables() {

    }
}
}
