/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class RunSeleniumTest {
    global RunSeleniumTest() {

    }
    @InvocableMethod(label='Invoke Selenium Test' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RunSeleniumTest.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Selenium Run Id' required=true)
    global Id runId;
    global InvocableVariables() {

    }
}
}
