/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class JsRemotingController {
    @RemoteAction
    global static String createAPIKey() {
        return null;
    }
    @RemoteAction
    global static List<String> getMetadataTypes(String orgId) {
        return null;
    }
    @RemoteAction
    global static void getVlocityDependencies(Id userStoryId, String jsonSelectedMetadata) {

    }
    @RemoteAction
    global static Boolean selectBranch(Id sObjectId, String fieldName, String branchName) {
        return null;
    }
}
