/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class ltng_MockupController extends VisualEditor.DynamicPickList {
    global ltng_MockupController() {

    }
    global override VisualEditor.DataRow getDefaultValue() {
        return null;
    }
    global override VisualEditor.DynamicPickListRows getValues() {
        return null;
    }
}
