/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class ElementsGenericExtensionController extends Q9.ElementsUtils {
    global Id recId {
        get;
        set;
    }
    global ElementsGenericExtensionController() {

    }
    webService static String getDiagramUrl(Id mapId) {
        return null;
    }
    @AuraEnabled
    global static String getUrlWithAuthLEX(String diagramId) {
        return null;
    }
    global static System.PageReference setElementsLoginTokenToCookie() {
        return null;
    }
}
