/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global virtual class qsyd_File extends qsyd_FE.qsyd_Item implements qsyd_FE.qsyd_IItem {
    global qsyd_File() {

    }
    global qsyd_File(Id id, Id folder, String label, String documentId, String entityId, String type, String ext, String owner, String tags, Decimal size, List<qsyd_FE.qsyd_Item> items) {

    }
    global qsyd_FE.qsyd_File convertToCanonical() {
        return null;
    }
    global qsyd_FE.qsyd_File load(qsyd_FE.qsyd_Item item) {
        return null;
    }
    global qsyd_FE.qsyd_File remove() {
        return null;
    }
    global qsyd_FE.qsyd_File save() {
        return null;
    }
}
