/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global virtual class qsyd_Folder extends qsyd_FE.qsyd_Item implements qsyd_FE.qsyd_IItem {
    global qsyd_Folder() {

    }
    global qsyd_Folder(Id id, String folder, String label, String entityId) {

    }
    global qsyd_Folder(Id id, String folder, String label, String entityId, List<qsyd_FE.qsyd_Item> items) {

    }
    global qsyd_FE.qsyd_Folder convertToCanonical() {
        return null;
    }
    global qsyd_FE.qsyd_Folder load(qsyd_FE.qsyd_Item item) {
        return null;
    }
    global qsyd_FE.qsyd_Folder remove() {
        return null;
    }
    global qsyd_FE.qsyd_Folder save() {
        return null;
    }
}
