/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class qsyd_FolderTemplate {
    global qsyd_FolderTemplate() {

    }
    global qsyd_FolderTemplate(String templateId, String entityId, String folderId) {

    }
    global qsyd_FE.qsyd_FolderTemplate generate() {
        return null;
    }
    global qsyd_FE.qsyd_FolderTemplate isValid() {
        return null;
    }
    global qsyd_FE.qsyd_FolderTemplate.qsyd_PaginatedFolderTemplates retrieveList(String filter, String sortBy, Integer pageSize, Integer pageOffset) {
        return null;
    }
    global qsyd_FE.qsyd_FolderTemplate rootFoldersDoNotExist() {
        return null;
    }
global class qsyd_PaginatedFolderTemplates {
    global qsyd_PaginatedFolderTemplates() {

    }
}
}
