/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class qsyd_FileList implements qsyd_FE.qsyd_IItemList {
    global qsyd_FileList() {

    }
    global qsyd_FileList(List<qsyd_FE.qsyd_Item> items) {

    }
    global qsyd_FE.qsyd_FileList convertToCanonical() {
        return null;
    }
    global qsyd_FE.qsyd_FileList convertToLogical() {
        return null;
    }
    global List<qsyd_FE__FileExplorerFile__c> getCanonicalList() {
        return null;
    }
    global List<qsyd_FE.qsyd_Item> getLogicalList() {
        return null;
    }
    global qsyd_FE.qsyd_FileList load(List<qsyd_FE.qsyd_Item> items) {
        return null;
    }
    global qsyd_FE.qsyd_FileList retrieve(String recordId) {
        return null;
    }
}
