/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class qsyd_FolderList implements qsyd_FE.qsyd_IItemList {
    global qsyd_FolderList() {

    }
    global qsyd_FolderList(List<qsyd_FE.qsyd_Item> items) {

    }
    global qsyd_FE.qsyd_FolderList convertToCanonical() {
        return null;
    }
    global qsyd_FE.qsyd_FolderList convertToLogical() {
        return null;
    }
    global List<qsyd_FE__FileExplorerFolder__c> getCanonicalList() {
        return null;
    }
    global List<qsyd_FE.qsyd_Item> getLogicalList() {
        return null;
    }
    global qsyd_FE.qsyd_FolderList load(List<qsyd_FE.qsyd_Item> items) {
        return null;
    }
    global qsyd_FE.qsyd_FolderList retrieve(String recordId) {
        return null;
    }
}
