/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class utilities {
    global utilities() {

    }
    global static void startSubscriptionQueue(Map<Id,SObject> newMap, Map<Id,SObject> oldMap, System.TriggerOperation triggerType, String objType) {

    }
}
