/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
@RestResource(urlMapping='/subscriptions')
global class subscriptions {
    global subscriptions() {

    }
    @HttpPost
    global static void createSubscription() {

    }
    @HttpDelete
    global static void deleteSubscription() {

    }
    @HttpPatch
    global static void renameSubChannel(String channelId, String channelName) {

    }
}
